### ISSUE TITLE
Exe displayed only the last run

### ISSUE THREAD

**Issue by bauergeorg** [NewestUser/github-workflow-dashboard#2]
I I tried the exe-file on windows. It worked very well! The output displayed only the last run. Did I forgot to add a parameter?

**Screenshot of the workflows at github**
![image](https://user-images.githubusercontent.com/79077565/154220271-063cac4d-dd0c-48cc-b431-a8f3bf766ec7.png)

**Screnshot of exe output**
![image](https://user-images.githubusercontent.com/79077565/154220544-3904fdd0-2b42-4af9-84ef-003304e2daac.png)

**Comment by NewestUser** [comment]
By default if you use the tool as a CLI (not in server mod) it fetches the latest runs for each of the workflows.

Would love your input on this. Would you expect that all available workflows are displayed or just the latest ones?

**Comment by bauergeorg** [comment]
I would love to have an option to select this or that.

**Comment by NewestUser** [comment]
Sounds reasonable. Will prepare a PR for that.

**Comment by NewestUser** [comment]
@bauergeorg I updated the binaries, please give those a try after which I will close this issue.

**Comment by bauergeorg** [comment]
@NewestUser It's work fine. Thanks a lot!
![Screenshot 2022-02-18 110111](https://user-images.githubusercontent.com/79077565/154660916-255d4c8d-925a-4702-8ef8-83a14ca77342.png)

Hint: If you set the option "-latest-only" to the end. Something went wrong.

**Comment by MZlatev-MDigital** [comment]
> Hint: If you set the option "-latest-only" to the end. Something went wrong.

The command line tool accepts first flags and then arguments: Example `github-workflow-dashboard-windows-386.exe <flags> <arguments>` or `github-workflow-dashboard-windows-386.exe -latest-only -server-mod -repo xxx -owner yyy workflow1 workflow2`
In your case when you provide `-latest-only` at the end of the command then that is treated as a workflow name. Thus you get the error saying that such a workflow is not found.

**Comment by bauergeorg** [comment]
Okay, thanks ;)
